---
title: "BCB420_Assignment"
author: "Mingzheng liu"
date: "30/01/2022"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---
 BCB420 Assignment 1 Data Selection and Initial Processing
---

## Packages required

```{r}
# if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
# if (!requireNamespace("GEOmetadb", quietly = TRUE)) BiocManager::install("GEOmetadb")
# if (!requireNamespace("ggplot2", quietly = TRUE)) install.packages("ggplot2")
library(BiocManager)
library(GEOmetadb)
library(ggplot2)
```
## Preparation
```{r}
if(!file.exists('GEOmetadb.sqlite')) getSQLiteFile()
file.info('GEOmetadb.sqlite')

con <- dbConnect(SQLite(),'GEOmetadb.sqlite')

geo_tables <- dbListTables(con)
geo_tables

dbListFields(con,'gse')

results <- dbGetQuery(con,'select * from gpl limit 5')
knitr::kable(head(results[,1:5]), format = "html")

num_platforms <- dbGetQuery(con,'select count(*) from gpl')
num_platforms

dbListFields(con,'gpl')

uniq_tech <- dbGetQuery(con,'select distinct technology from gpl')
nrow(uniq_tech)

knitr::kable(uniq_tech[1:2,], format = "html")

#create table w/ 2 cols so that all data fit on 
mod_table <- cbind(uniq_tech[1:(nrow(uniq_tech)/2), 1],
                   uniq_tech[((nrow(uniq_tech)/2)+1):nrow(uniq_tech), 1])

knitr::kable(mod_table, format = "html")

num_uniq_tech <- dbGetQuery(con,'select technology, count(*) from gpl group by technology')
colnames(num_uniq_tech)[2] <- "Num_Platforms"

plot_df <- num_uniq_tech[!is.na(num_uniq_tech$technology),]

p<-ggplot(data=plot_df, aes(technology, Num_Platforms)) +
  geom_col() + coord_flip()
p
```



### 1. Select an Expression Data Set

### 2. Clean the data and map to HUGO symbols

### 3. Apply Normalization

### 4. Interpret, and document



